CREATE TABLE "users" (
  "discord_id" bigint PRIMARY KEY,
  "balance" int NOT NULL DEFAULT 0,
  "last_claimed" timestamptz DEFAULT (now() - interval '13 hours'),
  "voice_time" bigint NOT NULL DEFAULT 0,
  "message_count" int NOT NULL DEFAULT 0,
  "married_id" bigint
);

CREATE TABLE "clans" (
  "clan_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "leader_id" bigint NOT NULL
);

CREATE TABLE "usersclans" (
  "discord_id" bigint,
  "clan_id" int,
  PRIMARY KEY ("discord_id", "clan_id"),
  FOREIGN KEY ("discord_id") REFERENCES "users" ("discord_id"),
  FOREIGN KEY ("clan_id") REFERENCES "clans" ("clan_id")
);

CREATE TABLE "transactions" (
  "discord_id" bigint NOT NULL,
  "type" int NOT NULL,
  "quantity" int NOT NULL,
  "description" text DEFAULT 'None',
  "datetime" timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY ("discord_id") REFERENCES "users" ("discord_id")
);

COMMENT ON COLUMN "transactions"."type" IS '1 = +; 0 = -';
COMMENT ON COLUMN "transactions"."description" IS 'from where';

ALTER TABLE "clans" ADD FOREIGN KEY ("leader_id") REFERENCES "users" ("discord_id");
ALTER DATABASE discord SET timezone TO 'UTC';